author: "Carlos Osuna"
category: "http"
summary: "HTTP POST user's messages to target URL when user is offline"
home: "https://github.com/Carlososuna11/mod_offline_http_post"
url: "https://github.com/Carlososuna11/mod_offline_http_post"